# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "lumo-cljs-1.10.1" = {
      name = "lumo-cljs";
      packageName = "lumo-cljs";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lumo-cljs/-/lumo-cljs-1.10.1.tgz";
        sha512 = "pqgygbEEnzOjFUxejr/jK7gRhuQx0acd3PLyJwkz4ZyVHWyzGGhUxwzgYX/df4wKm7Zixfp73G0S0PFXiNHULQ==";
      };
    };
    "ramda-0.27.0" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.27.0.tgz";
        sha512 = "pVzZdDpWwWqEVVLshWUHjNwuVP7SfcmPraYuqocJp1yo2U1R7P+5QAfDhdItkuoGqIBnBYrtPp7rEPqDn9HlZA==";
      };
    };
  };
  args = {
    name = "node2nix-project";
    packageName = "node2nix-project";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."lumo-cljs-1.10.1"
      sources."ramda-0.27.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}